// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel SDF

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

float4 pointBuffer;

float4 objectPointBuffer;
float

[numthreads(8,8,1)]
void SDF (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
}
